### ISSUE TITLE
Setup AzureDevOps build for staging

### ISSUE THREAD

**Issue by jayayala** [RevealBi/Documentation#1]
Deploy the current content to staging, using Azure DevOps.
@brianlagunas , Brian Wint

**Comment by brianlagunas** [comment]
Met with Brian W. today. He will help us implement this if needed. He can get us setup with our AzureDevops account. We need the Reveal Build team to work on setting this up for docs. Isn't that @TorreyBetts and @kkoynov?

**Comment by brianlagunas** [comment]
files need to be copied into the revealbi.io/help directory

**Comment by jayayala** [comment]
> Met with @brianwint. today. He will help us implement this if needed. He can get us setup with our AzureDevops account. We need the Reveal Build team to work on setting this up for docs. Isn't that @TorreyBetts and @kkoynov?

Vasil Mihalkov is the one from ES who works in our builds. I'll talk to him about this as well...

**Comment by brianlagunas** [comment]
@brianwint is taking the lead on our AzureDevOps efforts. Just sent an email to the team.

**Comment by brianwint** [comment]
staging site can be accessed at https://staging.revealbi.io/docfx/help/

**Comment by brianlagunas** [comment]
This is great! Thanks @brianwint. I'll let you know when we are ready to change the build paths.

**Comment by brianlagunas** [comment]
Just so everyone is aware, the `docfx` segment in the uri is just temporary. We have more work on our end before we are ready to start pushing the new docs to the proper `help` location.
