### ISSUE TITLE
[Topic] Load dashboard walk through

### ISSUE THREAD

**Issue by brianlagunas** [RevealBi/Documentation#19]
Create a topic for loading a dashbord following this hands-on ab

https://github.com/RevealBi/RevealRoadshow-2020/blob/master/HandsOnLab/Instructions/01-LoadDashboard.md

**Comment by KDelcheva** [comment]
Needs a review from Konstantin.

**Comment by brianlagunas** [comment]
I updated the loading dashboard topic
