### ISSUE TITLE
Review and Update SDK Diagrams

### ISSUE THREAD

**Issue by brianlagunas** [RevealBi/Documentation#22]
Review the current web and desktop diagrams and consider replacing them with 

![image](https://user-images.githubusercontent.com/835562/77968051-9f88cd80-72a3-11ea-835d-7891d8dbe178.png)

and

![image](https://user-images.githubusercontent.com/835562/77968062-a44d8180-72a3-11ea-8528-909ff05aa89a.png)

**Comment by KDelcheva** [comment]
Awaiting a review from Martin R.

**Comment by brianlagunas** [comment]
This is no longer relevant. These topics will be going away as they provide no value
