### ISSUE TITLE
[Bug] All API links are "404 not found" on the Japanese content.

### ISSUE THREAD

**Issue by jsakamotoIGJP** [RevealBi/Documentation#265]
### Description

All API links are "404 not found" on the Japanese content. If the API documents in Japanese are not ready yet, it would be better if those links were redirected to the English version for the time being.

- https://help.revealbi.io/ja/

### Screenshots

![movie-002](https://user-images.githubusercontent.com/102948935/212791803-0720c119-0fd1-4e3a-b04a-31a637774778.gif)

**Comment by brianlagunas** [comment]
Thanks for reporting this. This has been fixed and should be live within the hour.
