### ISSUE TITLE
Point builds to GitHub repository 

### ISSUE THREAD

**Issue by jayayala** [RevealBi/Documentation#3]
Ask Vasil to point documentation builds to get latest from GitHub repository.
@jayayala

**Comment by brianlagunas** [comment]
Wouldn't this be part of setting up an AzureDevOps build?

**Comment by jayayala** [comment]
You are right, I'll talk about this with Vasil Mihalkov.

**Comment by brianlagunas** [comment]
Closing as this is part of #1
