### ISSUE TITLE
[Bug] Overview page for the SDK states we have SDK for iOS and Android

### ISSUE THREAD

**Issue by kkoynov** [RevealBi/Documentation#40]
### Description

It is stated "Reveal SDK can be used to integrate Reveal into applications developed in multiple platforms and technologies: Web, Windows WPF, Windows Forms, iOS, and Android." Currently we don't have iOS & Android SDK.

- Topic Link:
http://help-staging.revealbi.io/en/developer/general/overview.html

**Comment by KDelcheva** [comment]
Fixed.
