### ISSUE TITLE
[Bug] problems in developer/general/setup-configuration-web.html page

### ISSUE THREAD

**Issue by kkoynov** [RevealBi/Documentation#42]
### Description

- Again we depend on .net v4.6.2
- There is a closing emphasis tag 
- We should remove the part at the end about IE11 support as currently the web sdk doesn't work on IE11 as it is the case with the app.

- Topic Link:
http://help-staging.revealbi.io/en/developer/general/setup-configuration-web.html

### Screenshots
![image](https://user-images.githubusercontent.com/7972319/82032672-3ec32200-96a4-11ea-867c-336715b6f9f6.png)
![image](https://user-images.githubusercontent.com/7972319/82032893-96618d80-96a4-11ea-8f96-3f8
![image](https://user-images.githubusercontent.com/7972319/82033124-f5270700-96a4-11ea-8483-2a2940111a0b.png)
bd74e6e0b.png)

**Comment by KDelcheva** [comment]
- "There is a closing emphasis tag" - where? Not sure I see what you mean by this. 

- Removed the whole "IE11 Support" section.

**Comment by KDelcheva** [comment]
Fixed
