### ISSUE TITLE
[Bug] SDK Create your first app topic is a bit outdated

### ISSUE THREAD

**Issue by kkoynov** [RevealBi/Documentation#44]
### Description

In the topic changing the theme of a sample dashboards is used as a sample modification. However there were some theme changes that we need to account for. There is a chance the github commit links are also not so accurate and might need updating and a check if these sample code is still working against latest version. The screenshots on the page are also out of date because of the theming changes we did recently. 

- Topic Link:
http://help-staging.revealbi.io/en/developer/web-sdk/create-first-app.html

**Comment by KDelcheva** [comment]
- "In the topic changing the theme of a sample dashboard is used as a sample modification." - after this, the dashboard is exported and used in the SDK 
- Github commit links still need a review

**Comment by KDelcheva** [comment]
- Step 4 needs a review from Konstantin.
- Github commits need to be verified.

**Comment by brianlagunas** [comment]
Looks like this has been addressed
