### ISSUE TITLE
[Bug] C# code highlighting is failing on string interpolation 

### ISSUE THREAD

**Issue by kkoynov** [RevealBi/Documentation#45]
### Description

Looks  like code highlighting is done by highlight.js. Found out this issue https://github.com/dotnet/docfx/issues/3226 pointing to an internal issue but it seems it's a private repo.

- Topic Link:
Any SDK topic with C# snippet that's using string interpolation - for example:
http://help-staging.revealbi.io/en/developer/web-sdk/using-the-server-sdk/loading-dashboards.html

**Comment by KDelcheva** [comment]
@brianlagunas, any ideas of a workaround? This looks like a known issue for the docfx team.

**Comment by brianlagunas** [comment]
No, but this is a very, very, very low priority.

**Comment by KDelcheva** [comment]
Ok, closing this one. I hope it gets resolved one day.
