### ISSUE TITLE
[Topic] Missing important information for the DIY vizualization

### ISSUE THREAD

**Issue by kkoynov** [RevealBi/Documentation#46]
## Description

Not sure if we need a separate topic or expand the existing one. Here are some pages we had for this in the ReportPlus(legacy):

- https://www.infragistics.com/help/reportplus/diy-visualization
- https://www.infragistics.com/help/reportplus/diy-reportplus-javascript
- https://www.infragistics.com/help/reportplus/creating-custom-visualization
- https://www.infragistics.com/help/reportplus/diy-visualizations-server

Most of the links above should be more or less applicable for Reveal, not sure about the last(Server) one.

- Topic Link:
http://help-staging.revealbi.io/en/data-visualizations/diy-visualizations.html

**Comment by brianlagunas** [comment]
Good catch. @jayayala @KDelcheva are these topics we should add? If so, I can modify the TOC to create a subtopic for these topics like:

DATA VISUALIZATIONS
      ......
      Do-It-Yourself Visualizations
            Overview
            JavaScript API
            Create a Custom Visualization
            Reveal Server and Custom Visualizations


Note, this will impact the redirect rules, so the sooner I know if we need to make this change the better.

**Comment by brianlagunas** [comment]
Also, having looked at this again, should these topics be moved out of the user docs where it is now and into the dev docs?

Maybe keep the `http://help-staging.revealbi.io/en/data-visualizations/diy-visualizations.html` topic is user docs, but then maybe have that topic link to the developer docs?

Thoughts?

**Comment by kkoynov** [comment]
These should all be in the user docs since all of this is related to the app first. I'm not aware of any sdk specifics. The content from the old R+ app should also go through a technical review so we're sure what part of it got moved to Reveal.

**Comment by KDelcheva** [comment]
This topic is part of the User docs. These are not called "DIY" visualizations anymore, but "Custom" visualizations. The topic needs a lot of updating so I removed it from the TOC for now. The information there is not useful the way it is now, anyway. 
I will leave this issue open to remind me to rewrite the topic as soon as possible.

**Comment by jayayala** [comment]
Custom Visualizations is now online...
https://help.revealbi.io/en/data-visualizations/visualization-types/diy-visualizations.html
