### ISSUE TITLE
[Bug] 404 error on Share link 

### ISSUE THREAD

**Issue by CMcGuigan10** [RevealBi/Documentation#49]
### Description

**Share** your team's dashboards with other teams and users in Reveal. 

Results in 404 

http://help-staging.revealbi.io/en/teams/overview.html

![image](https://user-images.githubusercontent.com/54678308/82229637-bd180200-98f8-11ea-9668-a9eaf82814a0.png)

**Comment by KDelcheva** [comment]
The link has been fixed.
