### ISSUE TITLE
[Bug] Missing image in Linking Dashboard doc

### ISSUE THREAD

**Issue by gmartinelli-ig** [RevealBi/Documentation#51]
### Description

Missing image in Linking Dashboard doc

- Topic Link:
/dashboards/dashboard-linking.html

### Screenshots

![image](https://user-images.githubusercontent.com/52332421/83303228-132b5600-a1d3-11ea-8620-a9ec6064a30d.png)

**Comment by brianlagunas** [comment]
no longer seems to be an issue
