### ISSUE TITLE
[Bug] Unaccurate sentence in Sharing a dashboard doc

### ISSUE THREAD

**Issue by gmartinelli-ig** [RevealBi/Documentation#52]
### Description
Here where it says "_Sharing a dashboard means users will get a local copy of your dashboard; they will not be able to edit your local copy._" is not accurate because it depends on the permissions set. 

**dashboards/sharing-dashboards/share-a-dashboard.html#access-permissions**

### Screenshots

![image](https://user-images.githubusercontent.com/52332421/83305513-4d96f200-a1d7-11ea-9d9c-0bd27c50d42c.png)

**Comment by KDelcheva** [comment]
Fixed.
