### ISSUE TITLE
[Bug] Missing final step when restoring cloud files connections for sharing

### ISSUE THREAD

**Issue by gmartinelli-ig** [RevealBi/Documentation#53]
### Description

When restoring cloud files connections for sharing, after seeing the message informing them the connections were successfully restored, user MUST save the dashboard in order to complete the process.

_Is an open discussion if we must automatically save the dashboard in this case or not._

**dashboards/sharing-dashboards/request-access-shared-dashboards-cloud-files.html**
- Topic Link:

### Screenshots
![image](https://user-images.githubusercontent.com/52332421/83306268-a450fb80-a1d8-11ea-9fc5-6db9dfe15161.png)

**Comment by KDelcheva** [comment]
Fixed.
