### ISSUE TITLE
[Bug] Export Data (Excel) description

### ISSUE THREAD

**Issue by gmartinelli-ig** [RevealBi/Documentation#54]
### Description

The menu option is Export Excel, and is not only an export of data, there are some visualizations that are also exported. 

- Topic Link:
/dashboards/exporting-dashboards/how-to-export-a-dashboard.html

### Screenshots

![image](https://user-images.githubusercontent.com/52332421/83426035-f6766480-a404-11ea-8963-f8baea331c54.png)

**Comment by KDelcheva** [comment]
Fixed
