### ISSUE TITLE
[Bug]Issues on http://help-staging.revealbi.io/en/release-information/third-party-software.html

### ISSUE THREAD

**Issue by kkoynov** [RevealBi/Documentation#56]
### Description
Broken links:

- http://www.jexcelapi.org/
- http://www.freerdp.com/2012/05/24/winpr-windows-portable-runtime/

WebSocket4Net 3rd party is listed twice

- Topic Link:
http://help-staging.revealbi.io/en/release-information/third-party-software.html

**Comment by KDelcheva** [comment]
Fixed.
